// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_revisions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createArtifactRevision = `-- name: CreateArtifactRevision :one
INSERT INTO artifact_revisions (
    tenant_id, user_id, task_id,
    name, kind,
    content_hash, content_size,
    action_type, prev_revision_id,
    source_invocation_id,
    delivery_step, execution_unit, phase,
    actor,
    is_current
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, true)
RETURNING id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current
`

type CreateArtifactRevisionParams struct {
	TenantID           string         `json:"tenant_id"`
	UserID             string         `json:"user_id"`
	TaskID             string         `json:"task_id"`
	Name               string         `json:"name"`
	Kind               string         `json:"kind"`
	ContentHash        string         `json:"content_hash"`
	ContentSize        int64          `json:"content_size"`
	ActionType         string         `json:"action_type"`
	PrevRevisionID     sql.NullString `json:"prev_revision_id"`
	SourceInvocationID sql.NullString `json:"source_invocation_id"`
	DeliveryStep       sql.NullString `json:"delivery_step"`
	ExecutionUnit      sql.NullString `json:"execution_unit"`
	Phase              sql.NullString `json:"phase"`
	Actor              string         `json:"actor"`
}

// Insert a new immutable revision. The caller (internal/artifacts.Service) is
// responsible for writing the FS blob first and for the prev_revision_id chain
// (it loads the prior current revision, passes its id here, then demotes it via
// DemoteArtifactRevision). source_invocation_id is NULL for human-authored
// edits. The execution coordinate (delivery_step / execution_unit / phase) is
// optional and inert when NULL — a single-unit run never fills it.
func (q *Queries) CreateArtifactRevision(ctx context.Context, arg CreateArtifactRevisionParams) (ArtifactRevision, error) {
	row := q.db.QueryRowContext(ctx, createArtifactRevision,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Name,
		arg.Kind,
		arg.ContentHash,
		arg.ContentSize,
		arg.ActionType,
		arg.PrevRevisionID,
		arg.SourceInvocationID,
		arg.DeliveryStep,
		arg.ExecutionUnit,
		arg.Phase,
		arg.Actor,
	)
	var i ArtifactRevision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Name,
		&i.Kind,
		&i.ContentHash,
		&i.ContentSize,
		&i.ActionType,
		&i.PrevRevisionID,
		&i.SourceInvocationID,
		&i.DeliveryStep,
		&i.ExecutionUnit,
		&i.Phase,
		&i.Actor,
		&i.CreatedAt,
		&i.IsCurrent,
	)
	return i, err
}

const currentArtifactRevisionForName = `-- name: CurrentArtifactRevisionForName :one
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions
WHERE task_id = $1 AND tenant_id = $2 AND name = $3 AND is_current = true
`

type CurrentArtifactRevisionForNameParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

// The revision a resume / next stage syncs into the worktree for (task_id,
// name). Backed by the partial unique index idx_artifact_rev_current; one row
// max. Returns no rows when the task has no revision of that name yet.
func (q *Queries) CurrentArtifactRevisionForName(ctx context.Context, arg CurrentArtifactRevisionForNameParams) (ArtifactRevision, error) {
	row := q.db.QueryRowContext(ctx, currentArtifactRevisionForName, arg.TaskID, arg.TenantID, arg.Name)
	var i ArtifactRevision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Name,
		&i.Kind,
		&i.ContentHash,
		&i.ContentSize,
		&i.ActionType,
		&i.PrevRevisionID,
		&i.SourceInvocationID,
		&i.DeliveryStep,
		&i.ExecutionUnit,
		&i.Phase,
		&i.Actor,
		&i.CreatedAt,
		&i.IsCurrent,
	)
	return i, err
}

const demoteArtifactRevisionIfCurrent = `-- name: DemoteArtifactRevisionIfCurrent :execrows
UPDATE artifact_revisions SET is_current = false
WHERE task_id = $1 AND name = $2 AND id = $3 AND is_current = true
`

type DemoteArtifactRevisionIfCurrentParams struct {
	TaskID string `json:"task_id"`
	Name   string `json:"name"`
	ID     string `json:"id"`
}

// Flip one specific revision of (task_id, name) from current to superseded.
// Pinning the id (rather than "whatever is current") is what makes the write
// safe under concurrency: the caller read that id inside this transaction, so
// an affected-row count of 0 means another writer moved the chain in between
// and the caller must abort with ErrRevisionConflict rather than chain onto a
// revision that is no longer current.
//
// Runs in the same transaction as CreateArtifactRevision so the
// idx_artifact_rev_current unique partial index never sees two currents at once.
func (q *Queries) DemoteArtifactRevisionIfCurrent(ctx context.Context, arg DemoteArtifactRevisionIfCurrentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, demoteArtifactRevisionIfCurrent, arg.TaskID, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getArtifactRevision = `-- name: GetArtifactRevision :one
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions WHERE id = $1 AND tenant_id = $2
`

type GetArtifactRevisionParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetArtifactRevision(ctx context.Context, arg GetArtifactRevisionParams) (ArtifactRevision, error) {
	row := q.db.QueryRowContext(ctx, getArtifactRevision, arg.ID, arg.TenantID)
	var i ArtifactRevision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Name,
		&i.Kind,
		&i.ContentHash,
		&i.ContentSize,
		&i.ActionType,
		&i.PrevRevisionID,
		&i.SourceInvocationID,
		&i.DeliveryStep,
		&i.ExecutionUnit,
		&i.Phase,
		&i.Actor,
		&i.CreatedAt,
		&i.IsCurrent,
	)
	return i, err
}

const listArtifactRevisionsForInvocation = `-- name: ListArtifactRevisionsForInvocation :many
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions
WHERE source_invocation_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type ListArtifactRevisionsForInvocationParams struct {
	SourceInvocationID sql.NullString `json:"source_invocation_id"`
	TenantID           string         `json:"tenant_id"`
}

// Revisions produced by a specific stage invocation. Backed by the partial
// index on source_invocation_id.
func (q *Queries) ListArtifactRevisionsForInvocation(ctx context.Context, arg ListArtifactRevisionsForInvocationParams) ([]ArtifactRevision, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactRevisionsForInvocation, arg.SourceInvocationID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactRevision
	for rows.Next() {
		var i ArtifactRevision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Name,
			&i.Kind,
			&i.ContentHash,
			&i.ContentSize,
			&i.ActionType,
			&i.PrevRevisionID,
			&i.SourceInvocationID,
			&i.DeliveryStep,
			&i.ExecutionUnit,
			&i.Phase,
			&i.Actor,
			&i.CreatedAt,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactRevisionsForTask = `-- name: ListArtifactRevisionsForTask :many
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions
WHERE task_id = $1 AND tenant_id = $2
ORDER BY name ASC, created_at DESC
`

type ListArtifactRevisionsForTaskParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

// All revisions for a task, newest first. Includes prior, non-current
// revisions so the audit trail reads in full.
func (q *Queries) ListArtifactRevisionsForTask(ctx context.Context, arg ListArtifactRevisionsForTaskParams) ([]ArtifactRevision, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactRevisionsForTask, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactRevision
	for rows.Next() {
		var i ArtifactRevision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Name,
			&i.Kind,
			&i.ContentHash,
			&i.ContentSize,
			&i.ActionType,
			&i.PrevRevisionID,
			&i.SourceInvocationID,
			&i.DeliveryStep,
			&i.ExecutionUnit,
			&i.Phase,
			&i.Actor,
			&i.CreatedAt,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentArtifactRevisionsForTask = `-- name: ListCurrentArtifactRevisionsForTask :many
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions
WHERE task_id = $1 AND tenant_id = $2 AND is_current = true
ORDER BY name ASC
`

type ListCurrentArtifactRevisionsForTaskParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

// The current revisions only — the snapshot a resume / comparison reads.
func (q *Queries) ListCurrentArtifactRevisionsForTask(ctx context.Context, arg ListCurrentArtifactRevisionsForTaskParams) ([]ArtifactRevision, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentArtifactRevisionsForTask, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactRevision
	for rows.Next() {
		var i ArtifactRevision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Name,
			&i.Kind,
			&i.ContentHash,
			&i.ContentSize,
			&i.ActionType,
			&i.PrevRevisionID,
			&i.SourceInvocationID,
			&i.DeliveryStep,
			&i.ExecutionUnit,
			&i.Phase,
			&i.Actor,
			&i.CreatedAt,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentArtifactRevisionForName = `-- name: LockCurrentArtifactRevisionForName :one
SELECT id, tenant_id, user_id, task_id, name, kind, content_hash, content_size, action_type, prev_revision_id, source_invocation_id, delivery_step, execution_unit, phase, actor, created_at, is_current FROM artifact_revisions
WHERE task_id = $1 AND tenant_id = $2 AND name = $3 AND is_current = true
FOR UPDATE
`

type LockCurrentArtifactRevisionForNameParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

// The same lookup as CurrentArtifactRevisionForName, but taking a row lock so
// the read-decide-write sequence in artifacts.SQLStore.Put is serialized
// against concurrent writers to the same (task_id, name). Must be called inside
// a transaction; a second writer blocks here until the first commits and then
// observes the new current revision.
//
// No row to lock means no current revision, which is the "first create" case:
// two racing first-creates are caught instead by the idx_artifact_rev_current
// unique partial index, and the loser's insert fails.
func (q *Queries) LockCurrentArtifactRevisionForName(ctx context.Context, arg LockCurrentArtifactRevisionForNameParams) (ArtifactRevision, error) {
	row := q.db.QueryRowContext(ctx, lockCurrentArtifactRevisionForName, arg.TaskID, arg.TenantID, arg.Name)
	var i ArtifactRevision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Name,
		&i.Kind,
		&i.ContentHash,
		&i.ContentSize,
		&i.ActionType,
		&i.PrevRevisionID,
		&i.SourceInvocationID,
		&i.DeliveryStep,
		&i.ExecutionUnit,
		&i.Phase,
		&i.Actor,
		&i.CreatedAt,
		&i.IsCurrent,
	)
	return i, err
}
