// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package sqlc

import (
	"context"
)

const createCheckpoint = `-- name: CreateCheckpoint :one
INSERT INTO task_checkpoints (tenant_id, user_id, task_id, label, commit_sha)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (task_id, label) DO UPDATE SET
    commit_sha = EXCLUDED.commit_sha,
    created_at = now()
RETURNING id, tenant_id, user_id, task_id, label, commit_sha, created_at
`

type CreateCheckpointParams struct {
	TenantID  string `json:"tenant_id"`
	UserID    string `json:"user_id"`
	TaskID    string `json:"task_id"`
	Label     string `json:"label"`
	CommitSha string `json:"commit_sha"`
}

// Upsert a boundary checkpoint (F.6.1 AC #1, #2). The orchestrator owns these;
// agents cannot. (task_id, label) is unique, so a retry after a crash that
// re-hits the same boundary replaces the SHA rather than duplicating. commit_sha
// is the immutable full SHA the worktree HEAD pointed at when the boundary was
// crossed.
func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (TaskCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, createCheckpoint,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Label,
		arg.CommitSha,
	)
	var i TaskCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Label,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const latestCheckpointForTask = `-- name: LatestCheckpointForTask :one
SELECT id, tenant_id, user_id, task_id, label, commit_sha, created_at FROM task_checkpoints
WHERE task_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestCheckpointForTaskParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

// The most recent checkpoint for a task — the restore target when the reconciler
// classifies a crashed worktree as restorable. Returns no rows if the task has
// no checkpoints yet (the reconciler then falls back to base_commit or surfaces
// for human attention).
func (q *Queries) LatestCheckpointForTask(ctx context.Context, arg LatestCheckpointForTaskParams) (TaskCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, latestCheckpointForTask, arg.TaskID, arg.TenantID)
	var i TaskCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Label,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckpointsForTask = `-- name: ListCheckpointsForTask :many
SELECT id, tenant_id, user_id, task_id, label, commit_sha, created_at FROM task_checkpoints
WHERE task_id = $1 AND tenant_id = $2
ORDER BY created_at
`

type ListCheckpointsForTaskParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

// Ordered oldest-first so the audit trail reads in execution order.
func (q *Queries) ListCheckpointsForTask(ctx context.Context, arg ListCheckpointsForTaskParams) ([]TaskCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsForTask, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCheckpoint
	for rows.Next() {
		var i TaskCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Label,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
