// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (tenant_id, user_id, task_id, type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, task_id, type, payload, created_at
`

type AppendEventParams struct {
	TenantID string          `json:"tenant_id"`
	UserID   string          `json:"user_id"`
	TaskID   string          `json:"task_id"`
	Type     string          `json:"type"`
	Payload  json.RawMessage `json:"payload"`
}

// Insert a row in the durable event log. The runner is the only caller in
// production; tests and the SSE handler read. id is monotonic, so Last-Event-ID
// is a simple "> last_id" tail.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Type,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, tenant_id, user_id, task_id, type, payload, created_at FROM events
WHERE tenant_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListEventsAfterParams struct {
	TenantID string `json:"tenant_id"`
	ID       int64  `json:"id"`
	Limit    int32  `json:"limit"`
}

// Tenant-global tail: events with id > afterID, ordered for SSE replay / live
// tail. Used by GET /api/v1/events. Last-Event-ID maps to afterID.
func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, arg.TenantID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfterTask = `-- name: ListEventsAfterTask :many
SELECT id, tenant_id, user_id, task_id, type, payload, created_at FROM events
WHERE tenant_id = $1 AND task_id = $2 AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListEventsAfterTaskParams struct {
	TenantID string `json:"tenant_id"`
	TaskID   string `json:"task_id"`
	ID       int64  `json:"id"`
	Limit    int32  `json:"limit"`
}

// Per-task tail: same shape, scoped to one task. Used by GET /tasks/{id}/events.
func (q *Queries) ListEventsAfterTask(ctx context.Context, arg ListEventsAfterTaskParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfterTask,
		arg.TenantID,
		arg.TaskID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
