// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const bumpHeartbeat = `-- name: BumpHeartbeat :exec
UPDATE jobs SET heartbeat_at = now()
WHERE id = $1 AND status = 'running'
`

// Refreshed by the worker during a run so the recovery pass can detect a dead
// worker (heartbeat older than the stale threshold).
func (q *Queries) BumpHeartbeat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, bumpHeartbeat, id)
	return err
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running', worker_id = $1, heartbeat_at = now(), attempts = attempts + 1
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending'
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, tenant_id, user_id, task_id, kind, status, worker_id, heartbeat_at, attempts, last_error, payload, created_at, finished_at
`

// Atomically claim the oldest pending job for worker_id. FOR UPDATE SKIP LOCKED
// lets multiple workers poll concurrently without blocking each other; each
// skips rows another worker holds. attempts increments on every claim so the
// poison-job bound (config.JobMaxAttempts, 04 §7.5) can cap retries.
func (q *Queries) ClaimNextJob(ctx context.Context, workerID sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, workerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Kind,
		&i.Status,
		&i.WorkerID,
		&i.HeartbeatAt,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET status = 'done', finished_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeJob, id)
	return err
}

const countRunningJobsForTask = `-- name: CountRunningJobsForTask :one
SELECT count(*)::int FROM jobs WHERE task_id = $1 AND status = 'running'
`

// Belt-and-suspenders: how many running jobs a task has. Used to guard against
// double-enqueue races (the FSM is the primary guard).
func (q *Queries) CountRunningJobsForTask(ctx context.Context, taskID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, countRunningJobsForTask, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (tenant_id, user_id, task_id, kind, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, task_id, kind, status, worker_id, heartbeat_at, attempts, last_error, payload, created_at, finished_at
`

type EnqueueJobParams struct {
	TenantID string          `json:"tenant_id"`
	UserID   string          `json:"user_id"`
	TaskID   string          `json:"task_id"`
	Kind     string          `json:"kind"`
	Payload  json.RawMessage `json:"payload"`
}

// Insert a pending job. Called by HTTP handlers transactionally with the FSM
// transition. kind ∈ {run, continue, advance, cancel}; payload carries the
// inputs the worker needs (edits/context/answers).
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Kind,
		arg.Payload,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Kind,
		&i.Status,
		&i.WorkerID,
		&i.HeartbeatAt,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET status = 'failed', last_error = $2, finished_at = now()
WHERE id = $1
`

type FailJobParams struct {
	ID        int64          `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

// Mark a job failed with the reason. The recovery pass (or the caller) decides
// whether the task moves to a paused state; this only records the job outcome.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.ID, arg.LastError)
	return err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :many
UPDATE jobs
SET status = 'pending', worker_id = NULL
WHERE id IN (
    SELECT j.id FROM jobs j
    WHERE j.status = 'running' AND j.heartbeat_at < $1
)
RETURNING id, tenant_id, user_id, task_id, kind, status, worker_id, heartbeat_at, attempts, last_error, payload, created_at, finished_at
`

// Recovery: re-queue jobs a worker died mid-run on (heartbeat older than the
// threshold). Returns the re-queued rows so the caller can log / emit events.
// The poison bound is enforced by the caller via attempts.
func (q *Queries) RequeueStaleJobs(ctx context.Context, heartbeatAt sql.NullTime) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, requeueStaleJobs, heartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TaskID,
			&i.Kind,
			&i.Status,
			&i.WorkerID,
			&i.HeartbeatAt,
			&i.Attempts,
			&i.LastError,
			&i.Payload,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
