// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_entries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const commitMemoryEntry = `-- name: CommitMemoryEntry :one
INSERT INTO memory_entries (
    tenant_id, user_id, project_id, scope, kind, title, body, keywords, source_task_id, source_stage
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, user_id, project_id, scope, kind, title, body, keywords, source_task_id, source_stage, status, created_at
`

type CommitMemoryEntryParams struct {
	TenantID     string         `json:"tenant_id"`
	UserID       string         `json:"user_id"`
	ProjectID    string         `json:"project_id"`
	Scope        string         `json:"scope"`
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Body         string         `json:"body"`
	Keywords     []string       `json:"keywords"`
	SourceTaskID sql.NullString `json:"source_task_id"`
	SourceStage  sql.NullString `json:"source_stage"`
}

// Insert only at task-done / final approval. The producing agent emitted these
// via memory_writes in result.json; they commit here.
func (q *Queries) CommitMemoryEntry(ctx context.Context, arg CommitMemoryEntryParams) (MemoryEntry, error) {
	row := q.db.QueryRowContext(ctx, commitMemoryEntry,
		arg.TenantID,
		arg.UserID,
		arg.ProjectID,
		arg.Scope,
		arg.Kind,
		arg.Title,
		arg.Body,
		pq.Array(arg.Keywords),
		arg.SourceTaskID,
		arg.SourceStage,
	)
	var i MemoryEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.Scope,
		&i.Kind,
		&i.Title,
		&i.Body,
		pq.Array(&i.Keywords),
		&i.SourceTaskID,
		&i.SourceStage,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const recentMemoryByProject = `-- name: RecentMemoryByProject :many
SELECT id, tenant_id, user_id, project_id, scope, kind, title, body, keywords, source_task_id, source_stage, status, created_at FROM memory_entries
WHERE project_id = $1 AND scope = 'project' AND status = 'active'
ORDER BY created_at DESC
LIMIT $2
`

type RecentMemoryByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
}

// The push path: most-recent-N decisions, recency-ordered. The baseline flywheel
// signal; zero agent cooperation required.
func (q *Queries) RecentMemoryByProject(ctx context.Context, arg RecentMemoryByProjectParams) ([]MemoryEntry, error) {
	rows, err := q.db.QueryContext(ctx, recentMemoryByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryEntry
	for rows.Next() {
		var i MemoryEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.Scope,
			&i.Kind,
			&i.Title,
			&i.Body,
			pq.Array(&i.Keywords),
			&i.SourceTaskID,
			&i.SourceStage,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoryByKeyword = `-- name: SearchMemoryByKeyword :many
SELECT id, tenant_id, user_id, project_id, scope, kind, title, body, keywords, source_task_id, source_stage, status, created_at FROM memory_entries
WHERE project_id = $1 AND scope = 'project' AND status = 'active'
  AND (title ILIKE '%' || $2 || '%' OR $2 = ANY(keywords) OR body ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3
`

type SearchMemoryByKeywordParams struct {
	ProjectID string         `json:"project_id"`
	Column2   sql.NullString `json:"column_2"`
	Limit     int32          `json:"limit"`
}

// The pull path: the named handle, recency-ordered. Must land before the
// flywheel test window closes, so relevance has a path and recency-only push
// doesn't false-negative the thesis.
func (q *Queries) SearchMemoryByKeyword(ctx context.Context, arg SearchMemoryByKeywordParams) ([]MemoryEntry, error) {
	rows, err := q.db.QueryContext(ctx, searchMemoryByKeyword, arg.ProjectID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryEntry
	for rows.Next() {
		var i MemoryEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.Scope,
			&i.Kind,
			&i.Title,
			&i.Body,
			pq.Array(&i.Keywords),
			&i.SourceTaskID,
			&i.SourceStage,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
