// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ArtifactRevision struct {
	ID                 string         `json:"id"`
	TenantID           string         `json:"tenant_id"`
	UserID             string         `json:"user_id"`
	TaskID             string         `json:"task_id"`
	Name               string         `json:"name"`
	Kind               string         `json:"kind"`
	ContentHash        string         `json:"content_hash"`
	ContentSize        int64          `json:"content_size"`
	ActionType         string         `json:"action_type"`
	PrevRevisionID     sql.NullString `json:"prev_revision_id"`
	SourceInvocationID sql.NullString `json:"source_invocation_id"`
	DeliveryStep       sql.NullString `json:"delivery_step"`
	ExecutionUnit      sql.NullString `json:"execution_unit"`
	Phase              sql.NullString `json:"phase"`
	Actor              string         `json:"actor"`
	CreatedAt          time.Time      `json:"created_at"`
	IsCurrent          bool           `json:"is_current"`
}

type Event struct {
	ID        int64           `json:"id"`
	TenantID  string          `json:"tenant_id"`
	UserID    string          `json:"user_id"`
	TaskID    sql.NullString  `json:"task_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type Job struct {
	ID          int64           `json:"id"`
	TenantID    string          `json:"tenant_id"`
	UserID      string          `json:"user_id"`
	TaskID      string          `json:"task_id"`
	Kind        string          `json:"kind"`
	Status      string          `json:"status"`
	WorkerID    sql.NullString  `json:"worker_id"`
	HeartbeatAt sql.NullTime    `json:"heartbeat_at"`
	Attempts    int32           `json:"attempts"`
	LastError   sql.NullString  `json:"last_error"`
	Payload     json.RawMessage `json:"payload"`
	CreatedAt   time.Time       `json:"created_at"`
	FinishedAt  sql.NullTime    `json:"finished_at"`
}

type MemoryEntry struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	UserID       string         `json:"user_id"`
	ProjectID    string         `json:"project_id"`
	Scope        string         `json:"scope"`
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Body         string         `json:"body"`
	Keywords     []string       `json:"keywords"`
	SourceTaskID sql.NullString `json:"source_task_id"`
	SourceStage  sql.NullString `json:"source_stage"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Project struct {
	ID              string    `json:"id"`
	TenantID        string    `json:"tenant_id"`
	UserID          string    `json:"user_id"`
	RepoPath        string    `json:"repo_path"`
	Name            string    `json:"name"`
	RelatedProjects []string  `json:"related_projects"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type StageInvocation struct {
	ID                string                `json:"id"`
	TenantID          string                `json:"tenant_id"`
	UserID            string                `json:"user_id"`
	TaskID            string                `json:"task_id"`
	Stage             string                `json:"stage"`
	Sequence          int32                 `json:"sequence"`
	SessionID         sql.NullString        `json:"session_id"`
	ResumeOf          sql.NullString        `json:"resume_of"`
	StopReason        sql.NullString        `json:"stop_reason"`
	PendingEdits      json.RawMessage       `json:"pending_edits"`
	Result            pqtype.NullRawMessage `json:"result"`
	StartedAt         time.Time             `json:"started_at"`
	FinishedAt        sql.NullTime          `json:"finished_at"`
	CapabilityProfile pqtype.NullRawMessage `json:"capability_profile"`
}

type Task struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Input        json.RawMessage `json:"input"`
	State        string          `json:"state"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	CurrentStage sql.NullString  `json:"current_stage"`
	BaseRef      string          `json:"base_ref"`
	BaseCommit   sql.NullString  `json:"base_commit"`
	ResultCommit sql.NullString  `json:"result_commit"`
}

type TaskCheckpoint struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	UserID    string    `json:"user_id"`
	TaskID    string    `json:"task_id"`
	Label     string    `json:"label"`
	CommitSha string    `json:"commit_sha"`
	CreatedAt time.Time `json:"created_at"`
}

type TaskManifest struct {
	ID         string          `json:"id"`
	TenantID   string          `json:"tenant_id"`
	UserID     string          `json:"user_id"`
	TaskID     string          `json:"task_id"`
	Body       json.RawMessage `json:"body"`
	SealedAt   sql.NullTime    `json:"sealed_at"`
	SealedBy   sql.NullString  `json:"sealed_by"`
	SealReason sql.NullString  `json:"seal_reason"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type TaskManifestCorrection struct {
	ID         string          `json:"id"`
	TenantID   string          `json:"tenant_id"`
	UserID     string          `json:"user_id"`
	ManifestID string          `json:"manifest_id"`
	Body       json.RawMessage `json:"body"`
	Reason     string          `json:"reason"`
	CreatedAt  time.Time       `json:"created_at"`
}
