// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Event struct {
	ID        int64           `json:"id"`
	TenantID  string          `json:"tenant_id"`
	UserID    string          `json:"user_id"`
	TaskID    string          `json:"task_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type MemoryEntry struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	UserID       string         `json:"user_id"`
	ProjectID    string         `json:"project_id"`
	Scope        string         `json:"scope"`
	Kind         string         `json:"kind"`
	Title        string         `json:"title"`
	Body         string         `json:"body"`
	Keywords     []string       `json:"keywords"`
	SourceTaskID string         `json:"source_task_id"`
	SourceStage  sql.NullString `json:"source_stage"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type StageInvocation struct {
	ID           string                `json:"id"`
	TenantID     string                `json:"tenant_id"`
	UserID       string                `json:"user_id"`
	TaskID       string                `json:"task_id"`
	Stage        string                `json:"stage"`
	Sequence     int32                 `json:"sequence"`
	SessionID    sql.NullString        `json:"session_id"`
	ResumeOf     string                `json:"resume_of"`
	StopReason   sql.NullString        `json:"stop_reason"`
	PendingEdits json.RawMessage       `json:"pending_edits"`
	Result       pqtype.NullRawMessage `json:"result"`
	StartedAt    time.Time             `json:"started_at"`
	FinishedAt   sql.NullTime          `json:"finished_at"`
}

type Task struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Input        json.RawMessage `json:"input"`
	State        string          `json:"state"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
