// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, user_id, repo_identity, repo_path, name, related_projects)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, repo_identity) DO UPDATE SET
    repo_path = EXCLUDED.repo_path,
    name = EXCLUDED.name,
    related_projects = EXCLUDED.related_projects,
    updated_at = now()
RETURNING id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at, repo_identity
`

type CreateProjectParams struct {
	TenantID        string   `json:"tenant_id"`
	UserID          string   `json:"user_id"`
	RepoIdentity    string   `json:"repo_identity"`
	RepoPath        string   `json:"repo_path"`
	Name            string   `json:"name"`
	RelatedProjects []string `json:"related_projects"`
}

// Idempotent registration keyed on the repository's identity, not its path:
// the same working copy (or a clone of the same history) under a new path
// updates the path and stays the same project, so a moved directory keeps its
// run history, memory and approvals. repo_identity is computed at the
// boundary (internal/repoid) and never accepted from a request body.
// Callers must pass a non-nil related_projects slice (the column is NOT
// NULL; pq.Array(nil) is NULL).
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.TenantID,
		arg.UserID,
		arg.RepoIdentity,
		arg.RepoPath,
		arg.Name,
		pq.Array(arg.RelatedProjects),
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoIdentity,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at, repo_identity FROM projects WHERE id = $1 AND tenant_id = $2
`

type GetProjectParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoIdentity,
	)
	return i, err
}

const getProjectByIdentity = `-- name: GetProjectByIdentity :one
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at, repo_identity FROM projects WHERE tenant_id = $1 AND repo_identity = $2
`

type GetProjectByIdentityParams struct {
	TenantID     string `json:"tenant_id"`
	RepoIdentity string `json:"repo_identity"`
}

// The pre-upsert read of the registration flow: the handler must know the
// project's previous repo_path (which the upsert overwrites) to resolve it
// and decide whether unfinished runs stay in the old copy or move with it.
func (q *Queries) GetProjectByIdentity(ctx context.Context, arg GetProjectByIdentityParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByIdentity, arg.TenantID, arg.RepoIdentity)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoIdentity,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at, repo_identity FROM projects
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RepoPath,
			&i.Name,
			pq.Array(&i.RelatedProjects),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoIdentity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
