// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, user_id, repo_path, name, related_projects)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, repo_path) DO UPDATE SET
    name = EXCLUDED.name,
    related_projects = EXCLUDED.related_projects,
    updated_at = now()
RETURNING id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID        string   `json:"tenant_id"`
	UserID          string   `json:"user_id"`
	RepoPath        string   `json:"repo_path"`
	Name            string   `json:"name"`
	RelatedProjects []string `json:"related_projects"`
}

// Idempotent registration: one repo_path = one project per tenant. Re-registering
// the same repo touches updated_at and applies the new fields (name, related set)
// rather than failing, so onboarding scripts are restart-safe. Callers must pass
// a non-nil related_projects slice (the column is NOT NULL; pq.Array(nil) is NULL).
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.TenantID,
		arg.UserID,
		arg.RepoPath,
		arg.Name,
		pq.Array(arg.RelatedProjects),
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at FROM projects WHERE id = $1 AND tenant_id = $2
`

type GetProjectParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByRepoPath = `-- name: GetProjectByRepoPath :one
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at FROM projects WHERE tenant_id = $1 AND repo_path = $2
`

type GetProjectByRepoPathParams struct {
	TenantID string `json:"tenant_id"`
	RepoPath string `json:"repo_path"`
}

// Lookup by repo_path within a tenant (used to resolve a project from a path
// without a round-trip of list-then-match).
func (q *Queries) GetProjectByRepoPath(ctx context.Context, arg GetProjectByRepoPathParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRepoPath, arg.TenantID, arg.RepoPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RepoPath,
		&i.Name,
		pq.Array(&i.RelatedProjects),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, user_id, repo_path, name, related_projects, created_at, updated_at FROM projects
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RepoPath,
			&i.Name,
			pq.Array(&i.RelatedProjects),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
