// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_publications.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimPublication = `-- name: ClaimPublication :one
UPDATE run_publications
SET state = 'publishing',
    attempts = attempts + 1,
    lease_owner = $3,
    lease_expires_at = $4,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
  AND (state <> 'publishing' OR lease_expires_at < now())
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at
`

type ClaimPublicationParams struct {
	TenantID       string         `json:"tenant_id"`
	RunID          string         `json:"run_id"`
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
}

// Lease the publication for one attempt: state moves to publishing, attempts
// increments, and the owner plus expiry are recorded. The WHERE clause is
// mutual exclusion by lease, not by row lock — the network call that follows
// must not run inside a transaction, so two workers racing here resolve by
// the conditional UPDATE, and the loser reads no row. A publishing row whose
// lease has expired is claimable again: its worker died mid-attempt.
func (q *Queries) ClaimPublication(ctx context.Context, arg ClaimPublicationParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, claimPublication,
		arg.TenantID,
		arg.RunID,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePublication = `-- name: EnsurePublication :one
INSERT INTO run_publications (tenant_id, user_id, run_id,
                              provider, remote_branch, published_commit, state)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (run_id) DO NOTHING
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at
`

type EnsurePublicationParams struct {
	TenantID        string `json:"tenant_id"`
	UserID          string `json:"user_id"`
	RunID           string `json:"run_id"`
	Provider        string `json:"provider"`
	RemoteBranch    string `json:"remote_branch"`
	PublishedCommit string `json:"published_commit"`
}

// Insert the run's publication row in state pending. The UNIQUE (run_id)
// index plus ON CONFLICT DO NOTHING is what makes a repeated request
// idempotent: the caller learns "already exists" from the empty return
// (sql.ErrNoRows) without a second round trip and falls back to
// GetPublicationForRun. The target columns stay empty here — the destination
// is derived at the first attempt and then frozen.
// user_id is whose name the run was created under; the publication actor is
// always the system, never a person.
func (q *Queries) EnsurePublication(ctx context.Context, arg EnsurePublicationParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, ensurePublication,
		arg.TenantID,
		arg.UserID,
		arg.RunID,
		arg.Provider,
		arg.RemoteBranch,
		arg.PublishedCommit,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findStalePublications = `-- name: FindStalePublications :many
SELECT publication.id, publication.tenant_id, publication.user_id, publication.run_id, publication.provider, publication.target_host, publication.target_owner, publication.target_repository, publication.base_branch, publication.remote_branch, publication.published_commit, publication.state, publication.pr_number, publication.pr_url, publication.pr_state, publication.branch_pushed_at, publication.published_at, publication.attempts, publication.last_error_code, publication.last_error_message, publication.lease_owner, publication.lease_expires_at, publication.created_at, publication.updated_at FROM run_publications publication
WHERE publication.tenant_id = $1
  AND publication.attempts < $2
  AND (
      (publication.state = 'pending' AND NOT EXISTS (
          SELECT 1 FROM jobs liveJob
          WHERE liveJob.run_id = publication.run_id
            AND liveJob.tenant_id = publication.tenant_id
            AND liveJob.kind = 'publish'
            AND liveJob.status IN ('pending', 'running')
      ))
      OR (
          publication.state = 'publishing'
          AND (publication.lease_expires_at IS NULL OR publication.lease_expires_at < now())
      )
  )
ORDER BY publication.created_at
`

type FindStalePublicationsParams struct {
	TenantID string `json:"tenant_id"`
	Attempts int32  `json:"attempts"`
}

// Reconciler probe: publications the queue lost or a worker died on —
// pending with no live publish job, or publishing with an expired lease.
// Bounded by attempts ($2, the job poison bound) so recovery cannot loop
// forever. failed and blocked rows are never returned: the system restores
// work it did not finish, it does not retry an outcome it recorded.
func (q *Queries) FindStalePublications(ctx context.Context, arg FindStalePublicationsParams) ([]RunPublication, error) {
	rows, err := q.db.QueryContext(ctx, findStalePublications, arg.TenantID, arg.Attempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunPublication
	for rows.Next() {
		var i RunPublication
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RunID,
			&i.Provider,
			&i.TargetHost,
			&i.TargetOwner,
			&i.TargetRepository,
			&i.BaseBranch,
			&i.RemoteBranch,
			&i.PublishedCommit,
			&i.State,
			&i.PrNumber,
			&i.PrUrl,
			&i.PrState,
			&i.BranchPushedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicationForRun = `-- name: GetPublicationForRun :one
SELECT id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at FROM run_publications
WHERE tenant_id = $1 AND run_id = $2
`

type GetPublicationForRunParams struct {
	TenantID string `json:"tenant_id"`
	RunID    string `json:"run_id"`
}

// The run's publication row, or no rows when no publication exists. Serves
// the read surface (GET .../publication, the final-review block) and the
// publish handler's reloads.
func (q *Queries) GetPublicationForRun(ctx context.Context, arg GetPublicationForRunParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, getPublicationForRun, arg.TenantID, arg.RunID)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPublicationFailure = `-- name: RecordPublicationFailure :one
UPDATE run_publications
SET state = $3,
    last_error_code = $4,
    last_error_message = $5,
    branch_pushed_at = COALESCE($6, branch_pushed_at),
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at
`

type RecordPublicationFailureParams struct {
	TenantID         string         `json:"tenant_id"`
	RunID            string         `json:"run_id"`
	State            string         `json:"state"`
	LastErrorCode    sql.NullString `json:"last_error_code"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	BranchPushedAt   sql.NullTime   `json:"branch_pushed_at"`
}

// Record a refused publication: the reason code from the closed vocabulary,
// the provider's message, and the state — failed when a retry can clear the
// reason, blocked when it cannot. branch_pushed_at keeps an earlier
// successful push: an attempt can push the branch and still fail the pull
// request, and the row must keep the half that succeeded. The lease is
// released.
func (q *Queries) RecordPublicationFailure(ctx context.Context, arg RecordPublicationFailureParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, recordPublicationFailure,
		arg.TenantID,
		arg.RunID,
		arg.State,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.BranchPushedAt,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPublicationSuccess = `-- name: RecordPublicationSuccess :one
UPDATE run_publications
SET state = 'published',
    target_host = COALESCE(NULLIF(target_host, ''), $3),
    target_owner = COALESCE(NULLIF(target_owner, ''), $4),
    target_repository = COALESCE(NULLIF(target_repository, ''), $5),
    base_branch = COALESCE(NULLIF(base_branch, ''), $6),
    pr_number = $7,
    pr_url = $8,
    pr_state = $9,
    branch_pushed_at = now(),
    published_at = now(),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_code = NULL,
    last_error_message = NULL,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at
`

type RecordPublicationSuccessParams struct {
	TenantID         string         `json:"tenant_id"`
	RunID            string         `json:"run_id"`
	TargetHost       string         `json:"target_host"`
	TargetOwner      string         `json:"target_owner"`
	TargetRepository string         `json:"target_repository"`
	BaseBranch       string         `json:"base_branch"`
	PrNumber         sql.NullInt32  `json:"pr_number"`
	PrUrl            sql.NullString `json:"pr_url"`
	PrState          sql.NullString `json:"pr_state"`
}

// Record a completed publication: the frozen target (written only when the
// row does not carry one yet — the target is derived once and a later attempt
// must not re-derive it against a moved remote), the pull request identity,
// and both outcome marks. State published requires branch_pushed_at and
// published_at together; the lease is released.
func (q *Queries) RecordPublicationSuccess(ctx context.Context, arg RecordPublicationSuccessParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, recordPublicationSuccess,
		arg.TenantID,
		arg.RunID,
		arg.TargetHost,
		arg.TargetOwner,
		arg.TargetRepository,
		arg.BaseBranch,
		arg.PrNumber,
		arg.PrUrl,
		arg.PrState,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
