// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_publications.sql

package sqlc

import (
	"context"
	"database/sql"
)

const claimPublication = `-- name: ClaimPublication :one
UPDATE run_publications
SET state = 'publishing',
    attempts = attempts + 1,
    lease_owner = $3,
    lease_expires_at = $4,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
  AND request_id = $5
  AND (state = 'pending' OR (state = 'publishing'
       AND (lease_expires_at IS NULL OR lease_expires_at < now())))
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id
`

type ClaimPublicationParams struct {
	TenantID       string         `json:"tenant_id"`
	RunID          string         `json:"run_id"`
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	RequestID      int64          `json:"request_id"`
}

// ClaimPublication leases pending work or an expired attempt for this request.
// Recorded outcomes require RequestPublication before another claim. The
// request id prevents older queued jobs from consuming that explicit retry.
// The attempt number fences outcome writes even when a job owner is reused.
// NULL leases are recoverable because no worker holds a valid lease then.
func (q *Queries) ClaimPublication(ctx context.Context, arg ClaimPublicationParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, claimPublication,
		arg.TenantID,
		arg.RunID,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.RequestID,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}

const ensurePublication = `-- name: EnsurePublication :one
INSERT INTO run_publications (tenant_id, user_id, run_id,
                              provider, remote_branch, published_commit, state)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (run_id) DO NOTHING
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id
`

type EnsurePublicationParams struct {
	TenantID        string `json:"tenant_id"`
	UserID          string `json:"user_id"`
	RunID           string `json:"run_id"`
	Provider        string `json:"provider"`
	RemoteBranch    string `json:"remote_branch"`
	PublishedCommit string `json:"published_commit"`
}

// Insert the run's publication row in state pending. The UNIQUE (run_id)
// index plus ON CONFLICT DO NOTHING is what makes a repeated request
// idempotent: the caller learns "already exists" from the empty return
// (sql.ErrNoRows) without a second round trip and falls back to
// GetPublicationForRun. The target columns stay empty here — the destination
// is derived at the first attempt and then frozen.
// user_id is whose name the run was created under; the publication actor is
// always the system, never a person.
func (q *Queries) EnsurePublication(ctx context.Context, arg EnsurePublicationParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, ensurePublication,
		arg.TenantID,
		arg.UserID,
		arg.RunID,
		arg.Provider,
		arg.RemoteBranch,
		arg.PublishedCommit,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}

const findStalePublications = `-- name: FindStalePublications :many
SELECT publication.id, publication.tenant_id, publication.user_id, publication.run_id, publication.provider, publication.target_host, publication.target_owner, publication.target_repository, publication.base_branch, publication.remote_branch, publication.published_commit, publication.state, publication.pr_number, publication.pr_url, publication.pr_state, publication.branch_pushed_at, publication.published_at, publication.attempts, publication.last_error_code, publication.last_error_message, publication.lease_owner, publication.lease_expires_at, publication.created_at, publication.updated_at, publication.request_id FROM run_publications publication
WHERE publication.tenant_id = $1
  AND publication.attempts < $2
  AND (SELECT COALESCE(sum(GREATEST(failed_job.attempts, 1)), 0)
       FROM jobs failed_job
       WHERE failed_job.tenant_id = publication.tenant_id
         AND failed_job.run_id = publication.run_id
         AND failed_job.kind = 'publish' AND failed_job.status = 'failed'
         AND COALESCE(failed_job.payload->>'request_id', '0') = publication.request_id::text
      ) < $2
  AND (
      (publication.state = 'pending' AND NOT EXISTS (
          SELECT 1 FROM jobs liveJob
          WHERE liveJob.run_id = publication.run_id
            AND liveJob.tenant_id = publication.tenant_id
            AND liveJob.kind = 'publish'
            AND COALESCE(liveJob.payload->>'request_id', '0') = publication.request_id::text
            AND liveJob.status IN ('pending', 'running')
      ))
      OR (
          publication.state = 'publishing'
          AND (publication.lease_expires_at IS NULL OR publication.lease_expires_at < now())
      )
  )
ORDER BY publication.created_at
`

type FindStalePublicationsParams struct {
	TenantID string `json:"tenant_id"`
	Attempts int32  `json:"attempts"`
}

// Reconciler probe: publications the queue lost or a worker died on —
// pending with no live publish job, or publishing with an expired lease.
// Bounded by publication attempts and failed job attempts ($2, the poison
// bound), including failures before a publication lease could be acquired.
// Failed jobs count against their request only. Recorded failed and blocked
// outcomes require an explicit retry.
func (q *Queries) FindStalePublications(ctx context.Context, arg FindStalePublicationsParams) ([]RunPublication, error) {
	rows, err := q.db.QueryContext(ctx, findStalePublications, arg.TenantID, arg.Attempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunPublication
	for rows.Next() {
		var i RunPublication
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RunID,
			&i.Provider,
			&i.TargetHost,
			&i.TargetOwner,
			&i.TargetRepository,
			&i.BaseBranch,
			&i.RemoteBranch,
			&i.PublishedCommit,
			&i.State,
			&i.PrNumber,
			&i.PrUrl,
			&i.PrState,
			&i.BranchPushedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicationForRun = `-- name: GetPublicationForRun :one
SELECT id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id FROM run_publications
WHERE tenant_id = $1 AND run_id = $2
`

type GetPublicationForRunParams struct {
	TenantID string `json:"tenant_id"`
	RunID    string `json:"run_id"`
}

// The run's publication row, or no rows when no publication exists. Serves
// the read surface (GET .../publication, the final-review block) and the
// publish handler's reloads.
func (q *Queries) GetPublicationForRun(ctx context.Context, arg GetPublicationForRunParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, getPublicationForRun, arg.TenantID, arg.RunID)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}

const recordPublicationFailure = `-- name: RecordPublicationFailure :one
UPDATE run_publications
SET state = $3,
    last_error_code = $4,
    last_error_message = $5,
    branch_pushed_at = COALESCE($6, branch_pushed_at),
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
  AND state = 'publishing' AND attempts = $7 AND lease_owner = $8
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id
`

type RecordPublicationFailureParams struct {
	TenantID         string         `json:"tenant_id"`
	RunID            string         `json:"run_id"`
	State            string         `json:"state"`
	LastErrorCode    sql.NullString `json:"last_error_code"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	BranchPushedAt   sql.NullTime   `json:"branch_pushed_at"`
	Attempts         int32          `json:"attempts"`
	LeaseOwner       sql.NullString `json:"lease_owner"`
}

// Record a refused publication: the reason code from the closed vocabulary,
// a safe diagnostic, and the state — failed when a retry can clear the
// reason, blocked when it cannot. branch_pushed_at keeps an earlier
// successful push: an attempt can push the branch and still fail the pull
// request, and the row must keep the half that succeeded. The lease is
// released. Only the current attempt and lease owner can record the outcome.
func (q *Queries) RecordPublicationFailure(ctx context.Context, arg RecordPublicationFailureParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, recordPublicationFailure,
		arg.TenantID,
		arg.RunID,
		arg.State,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.BranchPushedAt,
		arg.Attempts,
		arg.LeaseOwner,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}

const recordPublicationSuccess = `-- name: RecordPublicationSuccess :one
UPDATE run_publications
SET state = 'published',
    target_host = COALESCE(NULLIF(target_host, ''), $3),
    target_owner = COALESCE(NULLIF(target_owner, ''), $4),
    target_repository = COALESCE(NULLIF(target_repository, ''), $5),
    base_branch = COALESCE(NULLIF(base_branch, ''), $6),
    pr_number = $7,
    pr_url = $8,
    pr_state = $9,
    branch_pushed_at = now(),
    published_at = now(),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_error_code = NULL,
    last_error_message = NULL,
    updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
  AND state = 'publishing' AND attempts = $10 AND lease_owner = $11
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id
`

type RecordPublicationSuccessParams struct {
	TenantID         string         `json:"tenant_id"`
	RunID            string         `json:"run_id"`
	TargetHost       string         `json:"target_host"`
	TargetOwner      string         `json:"target_owner"`
	TargetRepository string         `json:"target_repository"`
	BaseBranch       string         `json:"base_branch"`
	PrNumber         sql.NullInt32  `json:"pr_number"`
	PrUrl            sql.NullString `json:"pr_url"`
	PrState          sql.NullString `json:"pr_state"`
	Attempts         int32          `json:"attempts"`
	LeaseOwner       sql.NullString `json:"lease_owner"`
}

// Record a completed publication: the frozen target (written only when the
// row does not carry one yet — the target is derived once and a later attempt
// must not re-derive it against a moved remote), the pull request identity,
// and both outcome marks. State published requires branch_pushed_at and
// published_at together; the lease is released. Only the current attempt
// and lease owner can record the outcome.
func (q *Queries) RecordPublicationSuccess(ctx context.Context, arg RecordPublicationSuccessParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, recordPublicationSuccess,
		arg.TenantID,
		arg.RunID,
		arg.TargetHost,
		arg.TargetOwner,
		arg.TargetRepository,
		arg.BaseBranch,
		arg.PrNumber,
		arg.PrUrl,
		arg.PrState,
		arg.Attempts,
		arg.LeaseOwner,
	)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}

const requestPublication = `-- name: RequestPublication :one
UPDATE run_publications
SET state = 'pending', request_id = request_id + 1,
    lease_owner = NULL, lease_expires_at = NULL, updated_at = now()
WHERE tenant_id = $1 AND run_id = $2
  AND (state <> 'publishing' OR lease_expires_at IS NULL OR lease_expires_at < now())
RETURNING id, tenant_id, user_id, run_id, provider, target_host, target_owner, target_repository, base_branch, remote_branch, published_commit, state, pr_number, pr_url, pr_state, branch_pushed_at, published_at, attempts, last_error_code, last_error_message, lease_owner, lease_expires_at, created_at, updated_at, request_id
`

type RequestPublicationParams struct {
	TenantID string `json:"tenant_id"`
	RunID    string `json:"run_id"`
}

// RequestPublication starts an explicit retry and invalidates older queued jobs.
// A concurrent claim with a live lease refuses the request atomically.
func (q *Queries) RequestPublication(ctx context.Context, arg RequestPublicationParams) (RunPublication, error) {
	row := q.db.QueryRowContext(ctx, requestPublication, arg.TenantID, arg.RunID)
	var i RunPublication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Provider,
		&i.TargetHost,
		&i.TargetOwner,
		&i.TargetRepository,
		&i.BaseBranch,
		&i.RemoteBranch,
		&i.PublishedCommit,
		&i.State,
		&i.PrNumber,
		&i.PrUrl,
		&i.PrState,
		&i.BranchPushedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
	)
	return i, err
}
