// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countActiveRunsOnCheckout = `-- name: CountActiveRunsOnCheckout :one
SELECT count(*) FROM runs
WHERE tenant_id = $1 AND project_id = $2 AND checkout_path = $3
  AND state NOT IN ('done', 'failed', 'cancelled')
`

type CountActiveRunsOnCheckoutParams struct {
	TenantID     string `json:"tenant_id"`
	ProjectID    string `json:"project_id"`
	CheckoutPath string `json:"checkout_path"`
}

// The second working copy: how many unfinished runs stay in the previous one.
// The registration response names this count so the split is visible at
// registration time, not when someone tries to continue a run.
func (q *Queries) CountActiveRunsOnCheckout(ctx context.Context, arg CountActiveRunsOnCheckoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRunsOnCheckout, arg.TenantID, arg.ProjectID, arg.CheckoutPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (tenant_id, user_id, project_id, pipeline_pack,
                  title, description, overrides, base_ref, state, route_source, route_reason, route_decided_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'created', NULLIF($9::text, ''),
        CASE WHEN $9::text = 'request' THEN 'pipeline_pack was set in POST /runs. Triage did not run for this run.' ELSE '' END,
        CASE WHEN $9::text = 'request' THEN now() ELSE NULL END)
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type CreateRunParams struct {
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Overrides    json.RawMessage `json:"overrides"`
	BaseRef      string          `json:"base_ref"`
	RouteSource  string          `json:"route_source"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.TenantID,
		arg.UserID,
		arg.ProjectID,
		arg.PipelinePack,
		arg.Title,
		arg.Description,
		arg.Overrides,
		arg.BaseRef,
		arg.RouteSource,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const findOrphanedRunningRuns = `-- name: FindOrphanedRunningRuns :many
SELECT runningrun.id, runningrun.tenant_id, runningrun.user_id, runningrun.project_id, runningrun.pipeline_pack, runningrun.title, runningrun.state, runningrun.created_at, runningrun.updated_at, runningrun.current_stage, runningrun.base_ref, runningrun.base_commit, runningrun.result_commit, runningrun.description, runningrun.overrides, runningrun.checkout_path, runningrun.pipeline_pack_origin, runningrun.stop_reason, runningrun.error, runningrun.cancel_reason, runningrun.route_source, runningrun.route_reason, runningrun.route_fallback_code, runningrun.route_fallback_message, runningrun.route_decided_at, runningrun.route_triage_invocation_id, runningrun.pause_requested_at, runningrun.previous_result_commit, runningrun.active_fix_request_revision_id FROM runs runningRun
WHERE runningRun.tenant_id = $1
  AND runningRun.state = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.run_id = runningRun.id
        AND j.tenant_id = runningRun.tenant_id
        AND j.status IN ('pending', 'running')
  )
ORDER BY runningRun.updated_at
`

// Reconciler probe (F.6.1 AC #6): runs whose state says they are running but
// have no live (pending or running) job. A crash between the FSM transition and
// EnqueueJob, or a worker that died and its job already failed, leaves the run
// here. The reconciler transitions these to paused_user_stop (interrupted) so a
// human explicitly resumes — safer than auto-replay of a half-run stage.
func (q *Queries) FindOrphanedRunningRuns(ctx context.Context, tenantID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedRunningRuns, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
			&i.PipelinePackOrigin,
			&i.StopReason,
			&i.Error,
			&i.CancelReason,
			&i.RouteSource,
			&i.RouteReason,
			&i.RouteFallbackCode,
			&i.RouteFallbackMessage,
			&i.RouteDecidedAt,
			&i.RouteTriageInvocationID,
			&i.PauseRequestedAt,
			&i.PreviousResultCommit,
			&i.ActiveFixRequestRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id FROM runs WHERE id = $1 AND tenant_id = $2
`

type GetRunParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.ID, arg.TenantID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id FROM runs WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type GetRunForUpdateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

// Locking read used by SetBaseCommit callers that need the post-resolution row
// even when the UPDATE matched zero rows (base_commit already set). FOR UPDATE
// serializes concurrent first-resolvers on the same run.
func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunForUpdate, arg.ID, arg.TenantID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id FROM runs
WHERE tenant_id = $1 AND project_id = $2
ORDER BY CASE WHEN state IN ('paused_open_questions', 'paused_gate', 'paused_user_stop', 'awaiting_final_review') THEN 0 ELSE 1 END,
         updated_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListRunsByProjectParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
			&i.PipelinePackOrigin,
			&i.StopReason,
			&i.Error,
			&i.CancelReason,
			&i.RouteSource,
			&i.RouteReason,
			&i.RouteFallbackCode,
			&i.RouteFallbackMessage,
			&i.RouteDecidedAt,
			&i.RouteTriageInvocationID,
			&i.PauseRequestedAt,
			&i.PreviousResultCommit,
			&i.ActiveFixRequestRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindActiveCheckouts = `-- name: RebindActiveCheckouts :many
UPDATE runs SET checkout_path = $4, updated_at = now()
WHERE tenant_id = $1 AND project_id = $2 AND checkout_path = $3
  AND state NOT IN ('done', 'failed', 'cancelled')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type RebindActiveCheckoutsParams struct {
	TenantID       string `json:"tenant_id"`
	ProjectID      string `json:"project_id"`
	CheckoutPath   string `json:"checkout_path"`
	CheckoutPath_2 string `json:"checkout_path_2"`
}

// The repository moved: the previous path no longer holds this repository, so
// the working copy is one and it relocated. Only non-terminal runs — a
// terminal run's checkout_path is a historical statement about where the work
// happened, and rewriting it would falsify the record.
func (q *Queries) RebindActiveCheckouts(ctx context.Context, arg RebindActiveCheckoutsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, rebindActiveCheckouts,
		arg.TenantID,
		arg.ProjectID,
		arg.CheckoutPath,
		arg.CheckoutPath_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
			&i.PipelinePackOrigin,
			&i.StopReason,
			&i.Error,
			&i.CancelReason,
			&i.RouteSource,
			&i.RouteReason,
			&i.RouteFallbackCode,
			&i.RouteFallbackMessage,
			&i.RouteDecidedAt,
			&i.RouteTriageInvocationID,
			&i.PauseRequestedAt,
			&i.PreviousResultCommit,
			&i.ActiveFixRequestRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenFinalReviewForFix = `-- name: ReopenFinalReviewForFix :one
UPDATE runs SET state = $5, current_stage = $3,
    previous_result_commit = result_commit, result_commit = NULL,
    active_fix_request_revision_id = $6,
    stop_reason = '', pause_requested_at = NULL, updated_at = now()
WHERE runs.id = $1 AND runs.tenant_id = $2 AND runs.state = 'awaiting_final_review'
  AND runs.result_commit = $4
  AND EXISTS (SELECT 1 FROM artifact_revisions
              WHERE artifact_revisions.run_id = runs.id AND artifact_revisions.tenant_id = runs.tenant_id
                AND artifact_revisions.name = 'final/fix-request.md'
                AND artifact_revisions.id = $6
                AND artifact_revisions.is_current = true)
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type ReopenFinalReviewForFixParams struct {
	ID            string         `json:"id"`
	TenantID      string         `json:"tenant_id"`
	CurrentStage  sql.NullString `json:"current_stage"`
	ResultCommit  sql.NullString `json:"result_commit"`
	NextState     string         `json:"next_state"`
	FixRevisionID sql.NullString `json:"fix_revision_id"`
}

// ReopenFinalReviewForFix enters the FSM result only when the accepted human
// revision is still current for the same reviewed commit.
func (q *Queries) ReopenFinalReviewForFix(ctx context.Context, arg ReopenFinalReviewForFixParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, reopenFinalReviewForFix,
		arg.ID,
		arg.TenantID,
		arg.CurrentStage,
		arg.ResultCommit,
		arg.NextState,
		arg.FixRevisionID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const reopenPlanGate = `-- name: ReopenPlanGate :one
UPDATE runs SET state = $4, current_stage = $3,
    stop_reason = 'plan_revision_drift', pause_requested_at = NULL,
    active_fix_request_revision_id = NULL,
    previous_result_commit = COALESCE(result_commit, previous_result_commit),
    result_commit = NULL, updated_at = now()
WHERE id = $1 AND tenant_id = $2
  AND state IN ('paused_gate', 'paused_open_questions', 'paused_user_stop', 'awaiting_final_review')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type ReopenPlanGateParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CurrentStage sql.NullString `json:"current_stage"`
	NextState    string         `json:"next_state"`
}

// ReopenPlanGate stores the FSM result with the artifact edit in one transaction.
// The plan revision and the pause cannot become visible separately.
func (q *Queries) ReopenPlanGate(ctx context.Context, arg ReopenPlanGateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, reopenPlanGate,
		arg.ID,
		arg.TenantID,
		arg.CurrentStage,
		arg.NextState,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const requestRunPause = `-- name: RequestRunPause :one
UPDATE runs SET pause_requested_at = COALESCE(pause_requested_at, now()), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND state = 'running'
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type RequestRunPauseParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) RequestRunPause(ctx context.Context, arg RequestRunPauseParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, requestRunPause, arg.ID, arg.TenantID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const selectRunRoute = `-- name: SelectRunRoute :one
UPDATE runs SET pipeline_pack = $3, route_source = $4, route_reason = $5,
    route_fallback_code = $6, route_fallback_message = $7,
    route_triage_invocation_id = $8, route_decided_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND route_source IS NULL AND state IN ('created', 'running')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type SelectRunRouteParams struct {
	ID                      string         `json:"id"`
	TenantID                string         `json:"tenant_id"`
	PipelinePack            string         `json:"pipeline_pack"`
	RouteSource             sql.NullString `json:"route_source"`
	RouteReason             string         `json:"route_reason"`
	RouteFallbackCode       string         `json:"route_fallback_code"`
	RouteFallbackMessage    string         `json:"route_fallback_message"`
	RouteTriageInvocationID sql.NullString `json:"route_triage_invocation_id"`
}

func (q *Queries) SelectRunRoute(ctx context.Context, arg SelectRunRouteParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, selectRunRoute,
		arg.ID,
		arg.TenantID,
		arg.PipelinePack,
		arg.RouteSource,
		arg.RouteReason,
		arg.RouteFallbackCode,
		arg.RouteFallbackMessage,
		arg.RouteTriageInvocationID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const setBaseCommit = `-- name: SetBaseCommit :one
UPDATE runs SET base_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND base_commit IS NULL
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type SetBaseCommitParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	BaseCommit sql.NullString `json:"base_commit"`
}

// Resolve-once: capture the immutable SHA the run's base_ref pointed at. The
// runner calls this before creating the worktree; the WHERE keeps it a no-op
// after the first capture so the recorded base cannot drift if base_ref is
// later moved. When the value is already pinned the UPDATE matches nothing
// and returns NO row (sql.ErrNoRows): the caller must read that as "another
// writer pinned first" and re-read the row, not as a failure.
func (q *Queries) SetBaseCommit(ctx context.Context, arg SetBaseCommitParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setBaseCommit, arg.ID, arg.TenantID, arg.BaseCommit)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const setCheckoutPath = `-- name: SetCheckoutPath :one
UPDATE runs SET checkout_path = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND checkout_path = ''
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type SetCheckoutPathParams struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	CheckoutPath string `json:"checkout_path"`
}

// Resolve-once, like SetBaseCommit: the run pins the working copy it executes
// in at first start and never re-resolves it, so re-registering the project
// from another clone cannot pull an in-flight run into a foreign directory.
// The empty string means "not pinned yet". When the copy is already pinned
// the UPDATE matches nothing and returns NO row (sql.ErrNoRows): the caller
// must read that as "another writer pinned first" and re-read the row, not as
// a failure.
func (q *Queries) SetCheckoutPath(ctx context.Context, arg SetCheckoutPathParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setCheckoutPath, arg.ID, arg.TenantID, arg.CheckoutPath)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const setPipelinePackOrigin = `-- name: SetPipelinePackOrigin :one
UPDATE runs SET pipeline_pack_origin = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND pipeline_pack_origin IS NULL
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type SetPipelinePackOriginParams struct {
	ID                 string         `json:"id"`
	TenantID           string         `json:"tenant_id"`
	PipelinePackOrigin sql.NullString `json:"pipeline_pack_origin"`
}

// Resolve-once, like SetBaseCommit: the run records where its pack's bytes
// came from (builtin / project / project+builtin) at the first effective
// resolution. The WHERE keeps it a no-op afterwards, so a later commit that
// changes the project's packs cannot rewrite what a running record says it
// executed. When the origin is already pinned the UPDATE matches nothing and
// returns NO row (sql.ErrNoRows): the caller reads that as "already pinned".
func (q *Queries) SetPipelinePackOrigin(ctx context.Context, arg SetPipelinePackOriginParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setPipelinePackOrigin, arg.ID, arg.TenantID, arg.PipelinePackOrigin)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const setResultCommit = `-- name: SetResultCommit :one
UPDATE runs SET result_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type SetResultCommitParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	ResultCommit sql.NullString `json:"result_commit"`
}

// Capture the tip of agentum/<run-id> at final approval. The branch + this
// commit remain resolvable after teardown; recorded once, on approve.
func (q *Queries) SetResultCommit(ctx context.Context, arg SetResultCommitParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setResultCommit, arg.ID, arg.TenantID, arg.ResultCommit)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const updateRunStage = `-- name: UpdateRunStage :one
UPDATE runs SET current_stage = $3, state = $4,
    stop_reason = CASE WHEN $4::text IN ('paused_open_questions', 'paused_gate', 'paused_user_stop') THEN $5::text ELSE '' END,
    error = '', cancel_reason = '',
    pause_requested_at = CASE WHEN $4::text = 'running' THEN pause_requested_at ELSE NULL END,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type UpdateRunStageParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CurrentStage sql.NullString `json:"current_stage"`
	State        string         `json:"state"`
	StopReason   string         `json:"stop_reason"`
}

// Set the runner's current position in the pack and (optionally) the state in
// one write. currentStage may be empty (e.g. clearing on terminal); state is
// always set. Used by the runner as it walks the pack's stages.
func (q *Queries) UpdateRunStage(ctx context.Context, arg UpdateRunStageParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStage,
		arg.ID,
		arg.TenantID,
		arg.CurrentStage,
		arg.State,
		arg.StopReason,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}

const updateRunState = `-- name: UpdateRunState :one
UPDATE runs SET state = $3,
    stop_reason = CASE WHEN $3::text IN ('paused_open_questions', 'paused_gate', 'paused_user_stop') THEN $4::text ELSE '' END,
    error = CASE WHEN $3::text = 'failed' THEN $5::text ELSE '' END,
    cancel_reason = CASE WHEN $3::text = 'cancelled' THEN $6::text ELSE '' END,
    pause_requested_at = CASE WHEN $3::text = 'running' THEN pause_requested_at ELSE NULL END,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path, pipeline_pack_origin, stop_reason, error, cancel_reason, route_source, route_reason, route_fallback_code, route_fallback_message, route_decided_at, route_triage_invocation_id, pause_requested_at, previous_result_commit, active_fix_request_revision_id
`

type UpdateRunStateParams struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	State        string `json:"state"`
	StopReason   string `json:"stop_reason"`
	Error        string `json:"error"`
	CancelReason string `json:"cancel_reason"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunState,
		arg.ID,
		arg.TenantID,
		arg.State,
		arg.StopReason,
		arg.Error,
		arg.CancelReason,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
		&i.PipelinePackOrigin,
		&i.StopReason,
		&i.Error,
		&i.CancelReason,
		&i.RouteSource,
		&i.RouteReason,
		&i.RouteFallbackCode,
		&i.RouteFallbackMessage,
		&i.RouteDecidedAt,
		&i.RouteTriageInvocationID,
		&i.PauseRequestedAt,
		&i.PreviousResultCommit,
		&i.ActiveFixRequestRevisionID,
	)
	return i, err
}
