// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countActiveRunsOnCheckout = `-- name: CountActiveRunsOnCheckout :one
SELECT count(*) FROM runs
WHERE tenant_id = $1 AND project_id = $2 AND checkout_path = $3
  AND state NOT IN ('done', 'failed', 'cancelled')
`

type CountActiveRunsOnCheckoutParams struct {
	TenantID     string `json:"tenant_id"`
	ProjectID    string `json:"project_id"`
	CheckoutPath string `json:"checkout_path"`
}

// The second working copy: how many unfinished runs stay in the previous one.
// The registration response names this count so the split is visible at
// registration time, not when someone tries to continue a run.
func (q *Queries) CountActiveRunsOnCheckout(ctx context.Context, arg CountActiveRunsOnCheckoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRunsOnCheckout, arg.TenantID, arg.ProjectID, arg.CheckoutPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (tenant_id, user_id, project_id, pipeline_pack,
                  title, description, overrides, base_ref, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'created')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type CreateRunParams struct {
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Overrides    json.RawMessage `json:"overrides"`
	BaseRef      string          `json:"base_ref"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.TenantID,
		arg.UserID,
		arg.ProjectID,
		arg.PipelinePack,
		arg.Title,
		arg.Description,
		arg.Overrides,
		arg.BaseRef,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const findOrphanedRunningRuns = `-- name: FindOrphanedRunningRuns :many
SELECT runningrun.id, runningrun.tenant_id, runningrun.user_id, runningrun.project_id, runningrun.pipeline_pack, runningrun.title, runningrun.state, runningrun.created_at, runningrun.updated_at, runningrun.current_stage, runningrun.base_ref, runningrun.base_commit, runningrun.result_commit, runningrun.description, runningrun.overrides, runningrun.checkout_path FROM runs runningRun
WHERE runningRun.tenant_id = $1
  AND runningRun.state = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.run_id = runningRun.id
        AND j.tenant_id = runningRun.tenant_id
        AND j.status IN ('pending', 'running')
  )
ORDER BY runningRun.updated_at
`

// Reconciler probe (F.6.1 AC #6): runs whose state says they are running but
// have no live (pending or running) job. A crash between the FSM transition and
// EnqueueJob, or a worker that died and its job already failed, leaves the run
// here. The reconciler transitions these to paused_user_stop (interrupted) so a
// human explicitly resumes — safer than auto-replay of a half-run stage.
func (q *Queries) FindOrphanedRunningRuns(ctx context.Context, tenantID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedRunningRuns, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path FROM runs WHERE id = $1 AND tenant_id = $2
`

type GetRunParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.ID, arg.TenantID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path FROM runs WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type GetRunForUpdateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

// Locking read used by SetBaseCommit callers that need the post-resolution row
// even when the UPDATE matched zero rows (base_commit already set). FOR UPDATE
// serializes concurrent first-resolvers on the same run.
func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunForUpdate, arg.ID, arg.TenantID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path FROM runs
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListRunsByProjectParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindActiveCheckouts = `-- name: RebindActiveCheckouts :many
UPDATE runs SET checkout_path = $4, updated_at = now()
WHERE tenant_id = $1 AND project_id = $2 AND checkout_path = $3
  AND state NOT IN ('done', 'failed', 'cancelled')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type RebindActiveCheckoutsParams struct {
	TenantID       string `json:"tenant_id"`
	ProjectID      string `json:"project_id"`
	CheckoutPath   string `json:"checkout_path"`
	CheckoutPath_2 string `json:"checkout_path_2"`
}

// The repository moved: the previous path no longer holds this repository, so
// the working copy is one and it relocated. Only non-terminal runs — a
// terminal run's checkout_path is a historical statement about where the work
// happened, and rewriting it would falsify the record.
func (q *Queries) RebindActiveCheckouts(ctx context.Context, arg RebindActiveCheckoutsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, rebindActiveCheckouts,
		arg.TenantID,
		arg.ProjectID,
		arg.CheckoutPath,
		arg.CheckoutPath_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
			&i.CheckoutPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBaseCommit = `-- name: SetBaseCommit :one
UPDATE runs SET base_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND base_commit IS NULL
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type SetBaseCommitParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	BaseCommit sql.NullString `json:"base_commit"`
}

// Resolve-once: capture the immutable SHA the run's base_ref pointed at. The
// runner calls this before creating the worktree; the WHERE keeps it a no-op
// after the first capture so the recorded base cannot drift if base_ref is
// later moved. When the value is already pinned the UPDATE matches nothing
// and returns NO row (sql.ErrNoRows): the caller must read that as "another
// writer pinned first" and re-read the row, not as a failure.
func (q *Queries) SetBaseCommit(ctx context.Context, arg SetBaseCommitParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setBaseCommit, arg.ID, arg.TenantID, arg.BaseCommit)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const setCheckoutPath = `-- name: SetCheckoutPath :one
UPDATE runs SET checkout_path = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND checkout_path = ''
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type SetCheckoutPathParams struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	CheckoutPath string `json:"checkout_path"`
}

// Resolve-once, like SetBaseCommit: the run pins the working copy it executes
// in at first start and never re-resolves it, so re-registering the project
// from another clone cannot pull an in-flight run into a foreign directory.
// The empty string means "not pinned yet". When the copy is already pinned
// the UPDATE matches nothing and returns NO row (sql.ErrNoRows): the caller
// must read that as "another writer pinned first" and re-read the row, not as
// a failure.
func (q *Queries) SetCheckoutPath(ctx context.Context, arg SetCheckoutPathParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setCheckoutPath, arg.ID, arg.TenantID, arg.CheckoutPath)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const setResultCommit = `-- name: SetResultCommit :one
UPDATE runs SET result_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type SetResultCommitParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	ResultCommit sql.NullString `json:"result_commit"`
}

// Capture the tip of agentum/<run-id> at final approval. The branch + this
// commit remain resolvable after teardown; recorded once, on approve.
func (q *Queries) SetResultCommit(ctx context.Context, arg SetResultCommitParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setResultCommit, arg.ID, arg.TenantID, arg.ResultCommit)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const updateRunStage = `-- name: UpdateRunStage :one
UPDATE runs SET current_stage = $3, state = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type UpdateRunStageParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CurrentStage sql.NullString `json:"current_stage"`
	State        string         `json:"state"`
}

// Set the runner's current position in the pack and (optionally) the state in
// one write. currentStage may be empty (e.g. clearing on terminal); state is
// always set. Used by the runner as it walks the pack's stages.
func (q *Queries) UpdateRunStage(ctx context.Context, arg UpdateRunStageParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStage,
		arg.ID,
		arg.TenantID,
		arg.CurrentStage,
		arg.State,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}

const updateRunState = `-- name: UpdateRunState :one
UPDATE runs SET state = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides, checkout_path
`

type UpdateRunStateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	State    string `json:"state"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunState, arg.ID, arg.TenantID, arg.State)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
		&i.CheckoutPath,
	)
	return i, err
}
