// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_invocations.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createStageInvocation = `-- name: CreateStageInvocation :one
INSERT INTO stage_invocations (tenant_id, user_id, run_id, stage, sequence, session_id, resume_of, stop_reason, capability_profile, cycle)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, user_id, run_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at, capability_profile, cycle
`

type CreateStageInvocationParams struct {
	TenantID          string                `json:"tenant_id"`
	UserID            string                `json:"user_id"`
	RunID             string                `json:"run_id"`
	Stage             string                `json:"stage"`
	Sequence          int32                 `json:"sequence"`
	SessionID         sql.NullString        `json:"session_id"`
	ResumeOf          sql.NullString        `json:"resume_of"`
	StopReason        sql.NullString        `json:"stop_reason"`
	CapabilityProfile pqtype.NullRawMessage `json:"capability_profile"`
	Cycle             int32                 `json:"cycle"`
}

func (q *Queries) CreateStageInvocation(ctx context.Context, arg CreateStageInvocationParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, createStageInvocation,
		arg.TenantID,
		arg.UserID,
		arg.RunID,
		arg.Stage,
		arg.Sequence,
		arg.SessionID,
		arg.ResumeOf,
		arg.StopReason,
		arg.CapabilityProfile,
		arg.Cycle,
	)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CapabilityProfile,
		&i.Cycle,
	)
	return i, err
}

const finishStageInvocation = `-- name: FinishStageInvocation :exec
UPDATE stage_invocations
SET session_id = $3, stop_reason = $4, result = $5, finished_at = now()
WHERE id = $1 AND tenant_id = $2
`

type FinishStageInvocationParams struct {
	ID         string                `json:"id"`
	TenantID   string                `json:"tenant_id"`
	SessionID  sql.NullString        `json:"session_id"`
	StopReason sql.NullString        `json:"stop_reason"`
	Result     pqtype.NullRawMessage `json:"result"`
}

// Record the parsed result.json + session_id + stop_reason on close. The runner
// calls this after the adapter returns. result is the parsed result.json (the
// file-derived fields); telemetry/session are stream-derived.
func (q *Queries) FinishStageInvocation(ctx context.Context, arg FinishStageInvocationParams) error {
	_, err := q.db.ExecContext(ctx, finishStageInvocation,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.StopReason,
		arg.Result,
	)
	return err
}

const getStageInvocation = `-- name: GetStageInvocation :one
SELECT id, tenant_id, user_id, run_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at, capability_profile, cycle FROM stage_invocations WHERE id = $1 AND tenant_id = $2
`

type GetStageInvocationParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetStageInvocation(ctx context.Context, arg GetStageInvocationParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, getStageInvocation, arg.ID, arg.TenantID)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CapabilityProfile,
		&i.Cycle,
	)
	return i, err
}

const latestStageForRun = `-- name: LatestStageForRun :one
SELECT id, tenant_id, user_id, run_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at, capability_profile, cycle FROM stage_invocations
WHERE run_id = $1 AND tenant_id = $2
ORDER BY sequence DESC
LIMIT 1
`

type LatestStageForRunParams struct {
	RunID    string `json:"run_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) LatestStageForRun(ctx context.Context, arg LatestStageForRunParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, latestStageForRun, arg.RunID, arg.TenantID)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RunID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CapabilityProfile,
		&i.Cycle,
	)
	return i, err
}

const listStageInvocationsForRun = `-- name: ListStageInvocationsForRun :many
SELECT id, tenant_id, user_id, run_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at, capability_profile, cycle FROM stage_invocations
WHERE run_id = $1 AND tenant_id = $2
ORDER BY sequence ASC
`

type ListStageInvocationsForRunParams struct {
	RunID    string `json:"run_id"`
	TenantID string `json:"tenant_id"`
}

// Ordered by sequence so each attempt is visible in run order; the cycle column
// distinguishes retries from resumes. Backs GET /runs/{id}/invocations.
func (q *Queries) ListStageInvocationsForRun(ctx context.Context, arg ListStageInvocationsForRunParams) ([]StageInvocation, error) {
	rows, err := q.db.QueryContext(ctx, listStageInvocationsForRun, arg.RunID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StageInvocation
	for rows.Next() {
		var i StageInvocation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RunID,
			&i.Stage,
			&i.Sequence,
			&i.SessionID,
			&i.ResumeOf,
			&i.StopReason,
			&i.PendingEdits,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CapabilityProfile,
			&i.Cycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCycleForStages = `-- name: MaxCycleForStages :one
SELECT COALESCE(MAX(cycle), -1)::int FROM stage_invocations
WHERE run_id = $1 AND tenant_id = $2 AND stage = ANY($3::text[])
`

type MaxCycleForStagesParams struct {
	RunID    string   `json:"run_id"`
	TenantID string   `json:"tenant_id"`
	Column3  []string `json:"column_3"`
}

// The durable fix-cycle counter: the highest cycle any of the given (fixer-
// role) stages has reached for this run. Returns -1 when none of the stages
// has run yet (MAX over zero rows is NULL; COALESCE to a sentinel that cannot
// be a real cycle, since cycles are >= 0). The runner maps -1 -> 0 entries.
// stage = ANY($3) takes the fixer set in one round-trip (pq.Array over pgx
// stdlib, already exercised by projects.related_projects).
func (q *Queries) MaxCycleForStages(ctx context.Context, arg MaxCycleForStagesParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, maxCycleForStages, arg.RunID, arg.TenantID, pq.Array(arg.Column3))
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setStageSession = `-- name: SetStageSession :exec
UPDATE stage_invocations SET session_id = $3
WHERE id = $1 AND tenant_id = $2
`

type SetStageSessionParams struct {
	ID        string         `json:"id"`
	TenantID  string         `json:"tenant_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) SetStageSession(ctx context.Context, arg SetStageSessionParams) error {
	_, err := q.db.ExecContext(ctx, setStageSession, arg.ID, arg.TenantID, arg.SessionID)
	return err
}

const setStageStop = `-- name: SetStageStop :exec
UPDATE stage_invocations
SET stop_reason = $3, finished_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetStageStopParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	StopReason sql.NullString `json:"stop_reason"`
}

func (q *Queries) SetStageStop(ctx context.Context, arg SetStageStopParams) error {
	_, err := q.db.ExecContext(ctx, setStageStop, arg.ID, arg.TenantID, arg.StopReason)
	return err
}
