// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_invocations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createStageInvocation = `-- name: CreateStageInvocation :one
INSERT INTO stage_invocations (tenant_id, user_id, task_id, stage, sequence, session_id, resume_of, stop_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, user_id, task_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at
`

type CreateStageInvocationParams struct {
	TenantID   string         `json:"tenant_id"`
	UserID     string         `json:"user_id"`
	TaskID     string         `json:"task_id"`
	Stage      string         `json:"stage"`
	Sequence   int32          `json:"sequence"`
	SessionID  sql.NullString `json:"session_id"`
	ResumeOf   string         `json:"resume_of"`
	StopReason sql.NullString `json:"stop_reason"`
}

func (q *Queries) CreateStageInvocation(ctx context.Context, arg CreateStageInvocationParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, createStageInvocation,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Stage,
		arg.Sequence,
		arg.SessionID,
		arg.ResumeOf,
		arg.StopReason,
	)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getStageInvocation = `-- name: GetStageInvocation :one
SELECT id, tenant_id, user_id, task_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at FROM stage_invocations WHERE id = $1 AND tenant_id = $2
`

type GetStageInvocationParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetStageInvocation(ctx context.Context, arg GetStageInvocationParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, getStageInvocation, arg.ID, arg.TenantID)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const latestStageForTask = `-- name: LatestStageForTask :one
SELECT id, tenant_id, user_id, task_id, stage, sequence, session_id, resume_of, stop_reason, pending_edits, result, started_at, finished_at FROM stage_invocations
WHERE task_id = $1 AND tenant_id = $2
ORDER BY sequence DESC
LIMIT 1
`

type LatestStageForTaskParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) LatestStageForTask(ctx context.Context, arg LatestStageForTaskParams) (StageInvocation, error) {
	row := q.db.QueryRowContext(ctx, latestStageForTask, arg.TaskID, arg.TenantID)
	var i StageInvocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Stage,
		&i.Sequence,
		&i.SessionID,
		&i.ResumeOf,
		&i.StopReason,
		&i.PendingEdits,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setStageSession = `-- name: SetStageSession :exec
UPDATE stage_invocations SET session_id = $3
WHERE id = $1 AND tenant_id = $2
`

type SetStageSessionParams struct {
	ID        string         `json:"id"`
	TenantID  string         `json:"tenant_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) SetStageSession(ctx context.Context, arg SetStageSessionParams) error {
	_, err := q.db.ExecContext(ctx, setStageSession, arg.ID, arg.TenantID, arg.SessionID)
	return err
}

const setStageStop = `-- name: SetStageStop :exec
UPDATE stage_invocations
SET stop_reason = $3, finished_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetStageStopParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	StopReason sql.NullString `json:"stop_reason"`
}

func (q *Queries) SetStageStop(ctx context.Context, arg SetStageStopParams) error {
	_, err := q.db.ExecContext(ctx, setStageStop, arg.ID, arg.TenantID, arg.StopReason)
	return err
}
