// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, user_id, project_id, pipeline_pack, title, input, state)
VALUES ($1, $2, $3, $4, $5, $6, 'created')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, input, state, created_at, updated_at
`

type CreateTaskParams struct {
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Input        json.RawMessage `json:"input"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TenantID,
		arg.UserID,
		arg.ProjectID,
		arg.PipelinePack,
		arg.Title,
		arg.Input,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.Input,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, input, state, created_at, updated_at FROM tasks WHERE id = $1 AND tenant_id = $2
`

type GetTaskParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.Input,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, input, state, created_at, updated_at FROM tasks
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTasksByProjectParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.Input,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskState = `-- name: UpdateTaskState :one
UPDATE tasks SET state = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, input, state, created_at, updated_at
`

type UpdateTaskStateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	State    string `json:"state"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskState, arg.ID, arg.TenantID, arg.State)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.Input,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
