// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_approvals.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO task_approvals (tenant_id, task_id, name, decision, artifact_revision_id, actor)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, task_id, name) DO NOTHING
RETURNING id, tenant_id, task_id, name, decision, artifact_revision_id, actor, created_at
`

type CreateApprovalParams struct {
	TenantID           string         `json:"tenant_id"`
	TaskID             string         `json:"task_id"`
	Name               string         `json:"name"`
	Decision           string         `json:"decision"`
	ArtifactRevisionID sql.NullString `json:"artifact_revision_id"`
	Actor              string         `json:"actor"`
}

// Insert one human-approval decision. The UNIQUE (tenant_id, task_id, name)
// index plus ON CONFLICT DO NOTHING is what makes a repeated approve idempotent:
// the handler learns "already decided" from the empty return (sql.ErrNoRows)
// without a second round trip, and a different decision on an already-decided
// gate is surfaced by GetApproval and stays a 409 at the handler. Returns no
// rows on conflict — the caller falls back to GetApproval to read the existing
// decision.
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (TaskApproval, error) {
	row := q.db.QueryRowContext(ctx, createApproval,
		arg.TenantID,
		arg.TaskID,
		arg.Name,
		arg.Decision,
		arg.ArtifactRevisionID,
		arg.Actor,
	)
	var i TaskApproval
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Name,
		&i.Decision,
		&i.ArtifactRevisionID,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, tenant_id, task_id, name, decision, artifact_revision_id, actor, created_at FROM task_approvals
WHERE tenant_id = $1 AND task_id = $2 AND name = $3
`

type GetApprovalParams struct {
	TenantID string `json:"tenant_id"`
	TaskID   string `json:"task_id"`
	Name     string `json:"name"`
}

// Read the decision row for one (task, name), or no rows when undecided. Used
// by the runner to decide whether the source_write withholding applies, and by
// the handler to implement idempotent approve/reject.
func (q *Queries) GetApproval(ctx context.Context, arg GetApprovalParams) (TaskApproval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, arg.TenantID, arg.TaskID, arg.Name)
	var i TaskApproval
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Name,
		&i.Decision,
		&i.ArtifactRevisionID,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalsForTask = `-- name: ListApprovalsForTask :many
SELECT id, tenant_id, task_id, name, decision, artifact_revision_id, actor, created_at FROM task_approvals
WHERE tenant_id = $1 AND task_id = $2
ORDER BY created_at ASC, id ASC
`

type ListApprovalsForTaskParams struct {
	TenantID string `json:"tenant_id"`
	TaskID   string `json:"task_id"`
}

// Every decision recorded for a task, oldest first. Feeds the final-review
// payload and the manifest's human_gates audit section.
func (q *Queries) ListApprovalsForTask(ctx context.Context, arg ListApprovalsForTaskParams) ([]TaskApproval, error) {
	rows, err := q.db.QueryContext(ctx, listApprovalsForTask, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskApproval
	for rows.Next() {
		var i TaskApproval
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.Name,
			&i.Decision,
			&i.ArtifactRevisionID,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
