// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_manifests.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addManifestEvidence = `-- name: AddManifestEvidence :one
UPDATE task_manifests
SET body = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND sealed_at IS NULL
RETURNING id, tenant_id, user_id, task_id, body, sealed_at, sealed_by, seal_reason, created_at, updated_at
`

type AddManifestEvidenceParams struct {
	ID       string          `json:"id"`
	TenantID string          `json:"tenant_id"`
	Body     json.RawMessage `json:"body"`
}

// Replace the body with an already-merged body the caller computed. Refuses to
// write when the manifest is already sealed — sealed_at IS NOT NULL means the
// body is immutable and any correction must go through task_manifest_corrections.
// Returns the updated row.
//
// This is a full replacement, not a JSONB merge, on purpose: the caller holds
// the row lock (GetManifestForUpdate) and has already merged the patch into the
// locked body in Go. A SQL-level `||` merge here would be a second, shallow
// merge whose top-level-key-only semantics silently drop nested evidence a
// concurrent writer just committed — the exact lost update the row lock exists
// to prevent. Replacing the whole body keeps the merge logic in one place (the
// Go merge functions) and makes it deep by construction.
func (q *Queries) AddManifestEvidence(ctx context.Context, arg AddManifestEvidenceParams) (TaskManifest, error) {
	row := q.db.QueryRowContext(ctx, addManifestEvidence, arg.ID, arg.TenantID, arg.Body)
	var i TaskManifest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.SealedAt,
		&i.SealedBy,
		&i.SealReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManifestCorrection = `-- name: CreateManifestCorrection :one
INSERT INTO task_manifest_corrections (tenant_id, user_id, manifest_id, body, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, manifest_id, body, reason, created_at
`

type CreateManifestCorrectionParams struct {
	TenantID   string          `json:"tenant_id"`
	UserID     string          `json:"user_id"`
	ManifestID string          `json:"manifest_id"`
	Body       json.RawMessage `json:"body"`
	Reason     string          `json:"reason"`
}

// A post-seal amendment. The body is a full corrected manifest snapshot; the
// sealed row is never edited. `reason` explains why the correction was made.
// Consumers read the sealed row + its corrections ordered by created_at.
func (q *Queries) CreateManifestCorrection(ctx context.Context, arg CreateManifestCorrectionParams) (TaskManifestCorrection, error) {
	row := q.db.QueryRowContext(ctx, createManifestCorrection,
		arg.TenantID,
		arg.UserID,
		arg.ManifestID,
		arg.Body,
		arg.Reason,
	)
	var i TaskManifestCorrection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ManifestID,
		&i.Body,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getManifest = `-- name: GetManifest :one
SELECT id, tenant_id, user_id, task_id, body, sealed_at, sealed_by, seal_reason, created_at, updated_at FROM task_manifests WHERE task_id = $1 AND tenant_id = $2
`

type GetManifestParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetManifest(ctx context.Context, arg GetManifestParams) (TaskManifest, error) {
	row := q.db.QueryRowContext(ctx, getManifest, arg.TaskID, arg.TenantID)
	var i TaskManifest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.SealedAt,
		&i.SealedBy,
		&i.SealReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManifestForUpdate = `-- name: GetManifestForUpdate :one
SELECT id, tenant_id, user_id, task_id, body, sealed_at, sealed_by, seal_reason, created_at, updated_at FROM task_manifests WHERE task_id = $1 AND tenant_id = $2 FOR UPDATE
`

type GetManifestForUpdateParams struct {
	TaskID   string `json:"task_id"`
	TenantID string `json:"tenant_id"`
}

// Locking read used by AddEvidence / SealManifest so two concurrent writers
// cannot interleave section writes. FOR UPDATE serializes them on the row.
func (q *Queries) GetManifestForUpdate(ctx context.Context, arg GetManifestForUpdateParams) (TaskManifest, error) {
	row := q.db.QueryRowContext(ctx, getManifestForUpdate, arg.TaskID, arg.TenantID)
	var i TaskManifest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.SealedAt,
		&i.SealedBy,
		&i.SealReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initManifest = `-- name: InitManifest :one
INSERT INTO task_manifests (tenant_id, user_id, task_id, body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id) DO NOTHING
RETURNING id, tenant_id, user_id, task_id, body, sealed_at, sealed_by, seal_reason, created_at, updated_at
`

type InitManifestParams struct {
	TenantID string          `json:"tenant_id"`
	UserID   string          `json:"user_id"`
	TaskID   string          `json:"task_id"`
	Body     json.RawMessage `json:"body"`
}

// Create the per-task manifest row. UNIQUE (task_id) makes a second Init a
// constraint violation — callers treat that as "already initialized" and move
// on to AddEvidence. The body starts empty; sections are filled by
// AddEvidence as evidence accumulates.
func (q *Queries) InitManifest(ctx context.Context, arg InitManifestParams) (TaskManifest, error) {
	row := q.db.QueryRowContext(ctx, initManifest,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Body,
	)
	var i TaskManifest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.SealedAt,
		&i.SealedBy,
		&i.SealReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestManifestCorrection = `-- name: LatestManifestCorrection :one
SELECT id, tenant_id, user_id, manifest_id, body, reason, created_at FROM task_manifest_corrections
WHERE manifest_id = $1 AND tenant_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestManifestCorrectionParams struct {
	ManifestID string `json:"manifest_id"`
	TenantID   string `json:"tenant_id"`
}

// The newest correction for a manifest, or no rows when none exist. Ordered by
// created_at DESC with an id DESC tiebreak: created_at has limited resolution
// (microseconds on Postgres), so two corrections written in the same transaction
// could otherwise order nondeterministically, and the latest one is the base the
// next correction chains onto — ordering must be stable. ListManifestCorrections
// mirrors this tiebreak (ASC, id ASC) so the two queries agree on order and Get,
// which takes the last row as the authoritative body, sees the true chain head.
func (q *Queries) LatestManifestCorrection(ctx context.Context, arg LatestManifestCorrectionParams) (TaskManifestCorrection, error) {
	row := q.db.QueryRowContext(ctx, latestManifestCorrection, arg.ManifestID, arg.TenantID)
	var i TaskManifestCorrection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ManifestID,
		&i.Body,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listManifestCorrections = `-- name: ListManifestCorrections :many
SELECT id, tenant_id, user_id, manifest_id, body, reason, created_at FROM task_manifest_corrections
WHERE manifest_id = $1 AND tenant_id = $2
ORDER BY created_at ASC, id ASC
`

type ListManifestCorrectionsParams struct {
	ManifestID string `json:"manifest_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) ListManifestCorrections(ctx context.Context, arg ListManifestCorrectionsParams) ([]TaskManifestCorrection, error) {
	rows, err := q.db.QueryContext(ctx, listManifestCorrections, arg.ManifestID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskManifestCorrection
	for rows.Next() {
		var i TaskManifestCorrection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ManifestID,
			&i.Body,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sealManifest = `-- name: SealManifest :one
UPDATE task_manifests
SET sealed_at = now(), sealed_by = $3, seal_reason = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND sealed_at IS NULL
RETURNING id, tenant_id, user_id, task_id, body, sealed_at, sealed_by, seal_reason, created_at, updated_at
`

type SealManifestParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	SealedBy   sql.NullString `json:"sealed_by"`
	SealReason sql.NullString `json:"seal_reason"`
}

// Set sealed_at + seal_reason + sealed_by. WHERE sealed_at IS NULL makes a
// second Seal a no-op; the caller re-reads to get the canonical row.
func (q *Queries) SealManifest(ctx context.Context, arg SealManifestParams) (TaskManifest, error) {
	row := q.db.QueryRowContext(ctx, sealManifest,
		arg.ID,
		arg.TenantID,
		arg.SealedBy,
		arg.SealReason,
	)
	var i TaskManifest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TaskID,
		&i.Body,
		&i.SealedAt,
		&i.SealedBy,
		&i.SealReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
