// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, user_id, project_id, pipeline_pack,
                   title, description, overrides, base_ref, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'created')
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides
`

type CreateTaskParams struct {
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	ProjectID    string          `json:"project_id"`
	PipelinePack string          `json:"pipeline_pack"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Overrides    json.RawMessage `json:"overrides"`
	BaseRef      string          `json:"base_ref"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TenantID,
		arg.UserID,
		arg.ProjectID,
		arg.PipelinePack,
		arg.Title,
		arg.Description,
		arg.Overrides,
		arg.BaseRef,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const findOrphanedRunningTasks = `-- name: FindOrphanedRunningTasks :many
SELECT t.id, t.tenant_id, t.user_id, t.project_id, t.pipeline_pack, t.title, t.state, t.created_at, t.updated_at, t.current_stage, t.base_ref, t.base_commit, t.result_commit, t.description, t.overrides FROM tasks t
WHERE t.tenant_id = $1
  AND t.state = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM jobs j
      WHERE j.task_id = t.id
        AND j.tenant_id = t.tenant_id
        AND j.status IN ('pending', 'running')
  )
ORDER BY t.updated_at
`

// Reconciler probe (F.6.1 AC #6): tasks whose state says they are running but
// have no live (pending or running) job. A crash between the FSM transition and
// EnqueueJob, or a worker that died and its job already failed, leaves the task
// here. The reconciler transitions these to paused_user_stop (interrupted) so a
// human explicitly resumes — safer than auto-replay of a half-run stage.
func (q *Queries) FindOrphanedRunningTasks(ctx context.Context, tenantID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedRunningTasks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides FROM tasks WHERE id = $1 AND tenant_id = $2
`

type GetTaskParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides FROM tasks WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type GetTaskForUpdateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

// Locking read used by SetBaseCommit callers that need the post-resolution row
// even when the UPDATE matched zero rows (base_commit already set). FOR UPDATE
// serializes concurrent first-resolvers on the same task.
func (q *Queries) GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides FROM tasks
WHERE tenant_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTasksByProjectParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject,
		arg.TenantID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ProjectID,
			&i.PipelinePack,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.BaseRef,
			&i.BaseCommit,
			&i.ResultCommit,
			&i.Description,
			&i.Overrides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBaseCommit = `-- name: SetBaseCommit :one
UPDATE tasks SET base_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND base_commit IS NULL
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides
`

type SetBaseCommitParams struct {
	ID         string         `json:"id"`
	TenantID   string         `json:"tenant_id"`
	BaseCommit sql.NullString `json:"base_commit"`
}

// Resolve-once: capture the immutable SHA the task's base_ref pointed at. The
// runner calls this before creating the worktree; it must be a no-op after the
// first capture (WHERE base_commit IS NULL) so the recorded base cannot drift
// if base_ref is later moved. Returns the row whether or not it changed.
func (q *Queries) SetBaseCommit(ctx context.Context, arg SetBaseCommitParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, setBaseCommit, arg.ID, arg.TenantID, arg.BaseCommit)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const setResultCommit = `-- name: SetResultCommit :one
UPDATE tasks SET result_commit = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides
`

type SetResultCommitParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	ResultCommit sql.NullString `json:"result_commit"`
}

// Capture the tip of agentum/<task-id> at final approval. The branch + this
// commit remain resolvable after teardown; recorded once, on approve.
func (q *Queries) SetResultCommit(ctx context.Context, arg SetResultCommitParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, setResultCommit, arg.ID, arg.TenantID, arg.ResultCommit)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const updateTaskStage = `-- name: UpdateTaskStage :one
UPDATE tasks SET current_stage = $3, state = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides
`

type UpdateTaskStageParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CurrentStage sql.NullString `json:"current_stage"`
	State        string         `json:"state"`
}

// Set the runner's current position in the pack and (optionally) the state in
// one write. currentStage may be empty (e.g. clearing on terminal); state is
// always set. Used by the runner as it walks the pack's stages.
func (q *Queries) UpdateTaskStage(ctx context.Context, arg UpdateTaskStageParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStage,
		arg.ID,
		arg.TenantID,
		arg.CurrentStage,
		arg.State,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}

const updateTaskState = `-- name: UpdateTaskState :one
UPDATE tasks SET state = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, project_id, pipeline_pack, title, state, created_at, updated_at, current_stage, base_ref, base_commit, result_commit, description, overrides
`

type UpdateTaskStateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	State    string `json:"state"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskState, arg.ID, arg.TenantID, arg.State)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ProjectID,
		&i.PipelinePack,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.BaseRef,
		&i.BaseCommit,
		&i.ResultCommit,
		&i.Description,
		&i.Overrides,
	)
	return i, err
}
